run:
  timeout: 5m
  tests: true
  skip-dirs:
    - cmd/embed
    - cmd/embed-app

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/mliezun/caddy-snake

issues:
  exclude-dirs:
    - docs
    - cmd/embed
    - cmd/embed-app
