---
name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    env:
      GOEXPERIMENT: cgocheck2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: |
            go.sum
      - name: Install Xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -yyqq
          sudo apt-get install -yyqq software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -yyqq python${{ matrix.python-version }}-dev python${{ matrix.python-version }}-venv
          sudo cp /usr/lib/x86_64-linux-gnu/pkgconfig/python-${{ matrix.python-version }}-embed.pc /usr/lib/x86_64-linux-gnu/pkgconfig/python3-embed.pc || true
          python${{ matrix.python-version }} -m venv venv
          source venv/bin/activate
          pip install Flask
      - name: Install global python dependencies
        run: sudo pip install requests
      - name: Run module tests
        run: go test -race -v ./...
      - name: Build the server
        working-directory: examples/
        run: CGO_ENABLED=1 xcaddy build --with github.com/mliezun/caddy-snake=..
      - name: Run integration tests
        working-directory: examples/
        run: |
          PYTHONPATH="../venv/lib/python${{ matrix.python-version }}/site-packages/" ./caddy run --config Caddyfile &
          sleep 10
          python ../examples_test.py
